# Generated by Django 3.1.7 on 2021-06-29 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210629_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='store.categorie'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='store.discount'),
        ),
    ]
