# Generated by Django 3.1.7 on 2021-06-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product_attr_id',
            new_name='product',
        ),
    ]
