# Generated by Django 3.1.7 on 2021-06-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210629_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_attributes',
            name='image',
            field=models.ImageField(default='', upload_to='store/images'),
        ),
    ]
