# Generated by Django 3.1.7 on 2021-07-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210702_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(default='', upload_to='store/images'),
        ),
    ]
